import { describe, expect, it } from "vitest";
import { connectorSetup } from "../src/lib/connectorSetup";

const allowedEnvVars = new Set([
  "WAIT_HALOPSA_BASE_URL", "WAIT_HALOPSA_CLIENT_ID", "WAIT_HALOPSA_CLIENT_SECRET", "WAIT_HALOPSA_TENANT",
  "WAIT_HALOPSA_TOKEN_URL", "WAIT_HALOPSA_TICKET_WRITE_ENDPOINT", "WAIT_HALOPSA_ACTION_WRITE_ENDPOINT", "WAIT_HALOPSA_CLIENT_MAP_JSON",
  "WAIT_CONNECTWISE_BASE_URL", "WAIT_CONNECTWISE_COMPANY", "WAIT_CONNECTWISE_PUBLIC_KEY", "WAIT_CONNECTWISE_PRIVATE_KEY",
  "WAIT_CONNECTWISE_CLIENT_ID", "WAIT_CONNECTWISE_API_VERSION", "WAIT_CONNECTWISE_PAGE_SIZE",
  "WAIT_HUDU_BASE_URL", "WAIT_HUDU_API_KEY", "WAIT_HUDU_PAGE_SIZE",
  "WAIT_ITGLUE_BASE_URL", "WAIT_ITGLUE_API_KEY", "WAIT_ITGLUE_PAGE_SIZE",
  "WAIT_CONFLUENCE_BASE_URL", "WAIT_CONFLUENCE_EMAIL", "WAIT_CONFLUENCE_API_TOKEN", "WAIT_CONFLUENCE_PAGE_SIZE",
  "WAIT_NOTION_BASE_URL", "WAIT_NOTION_API_TOKEN", "WAIT_NOTION_VERSION", "WAIT_NOTION_PAGE_SIZE",
  "WAIT_NOTION_CLIENT_PAGE_MAP_JSON", "WAIT_NOTION_CLIENT_DATA_SOURCE_MAP_JSON",
  "WAIT_SHAREPOINT_BASE_URL", "WAIT_SHAREPOINT_ACCESS_TOKEN", "WAIT_SHAREPOINT_PAGE_SIZE",
  "WAIT_SYNCRO_BASE_URL", "WAIT_SYNCRO_API_TOKEN",
  "WAIT_SERVICENOW_BASE_URL", "WAIT_SERVICENOW_USERNAME", "WAIT_SERVICENOW_PASSWORD", "WAIT_SERVICENOW_API_VERSION", "WAIT_SERVICENOW_PAGE_SIZE",
  "WAIT_AUTOTASK_BASE_URL", "WAIT_AUTOTASK_USERNAME", "WAIT_AUTOTASK_SECRET", "WAIT_AUTOTASK_INTEGRATION_CODE", "WAIT_AUTOTASK_PAGE_SIZE",
  "WAIT_M365_GRAPH_BASE_URL", "WAIT_M365_ACCESS_TOKEN", "WAIT_M365_PAGE_SIZE",
  "WAIT_TIMEZEST_BASE_URL", "WAIT_TIMEZEST_API_KEY", "WAIT_TIMEZEST_CLIENT_MAP_JSON",
  "WAIT_SCALEPAD_BASE_URL", "WAIT_SCALEPAD_API_KEY", "WAIT_SCALEPAD_CLIENT_MAP_JSON", "WAIT_SCALEPAD_RISK_TENANT_MAP_JSON",
  "WAIT_SCALEPAD_COMPLIANCE_CLIENT_MAP_JSON", "WAIT_SCALEPAD_LIFECYCLE_CLIENT_MAP_JSON",
  "WAIT_NINJAONE_BASE_URL", "WAIT_NINJAONE_ACCESS_TOKEN", "WAIT_NINJAONE_ORGANIZATION_MAP_JSON", "WAIT_NINJAONE_PAGE_SIZE",
  "WAIT_DATTORMM_BASE_URL", "WAIT_DATTORMM_ACCESS_TOKEN", "WAIT_DATTORMM_SITE_MAP_JSON", "WAIT_DATTORMM_PAGE_SIZE",
  "WAIT_NSIGHT_BASE_URL", "WAIT_NSIGHT_API_KEY", "WAIT_NSIGHT_CLIENT_MAP_JSON",
  "WAIT_NCENTRAL_BASE_URL", "WAIT_NCENTRAL_ACCESS_TOKEN", "WAIT_NCENTRAL_ORG_UNIT_MAP_JSON", "WAIT_NCENTRAL_PAGE_SIZE",
  "WAIT_KASEYA_RMM_BASE_URL", "WAIT_KASEYA_RMM_TOKEN_ID", "WAIT_KASEYA_RMM_TOKEN_SECRET", "WAIT_KASEYA_RMM_ORGANIZATION_MAP_JSON", "WAIT_KASEYA_RMM_PAGE_SIZE",
  "WAIT_SCREENCONNECT_BASE_URL", "WAIT_SCREENCONNECT_EXTENSION_ID", "WAIT_SCREENCONNECT_AUTH_SECRET", "WAIT_SCREENCONNECT_ORIGIN",
  "WAIT_SCREENCONNECT_CLIENT_SESSIONS_MAP_JSON", "WAIT_SCREENCONNECT_SCRIPT_CATALOG_JSON"
]);

describe("connector setup metadata", () => {
  it("documents the 14 connector cards and only verified WAIT environment names", () => {
    expect(Object.keys(connectorSetup)).toEqual([
      "halopsa", "connectwise", "hudu", "itglue", "confluence", "notion", "sharepoint",
      "syncro", "servicenow", "autotask", "m365", "timezest", "scalepad", "rmm"
    ]);

    const envVars = Object.values(connectorSetup).flatMap((setup) => setup.envVars);
    expect(envVars.every((envVar) => allowedEnvVars.has(envVar))).toBe(true);
    expect(new Set(envVars).size).toBe(envVars.length);
  });
});
